---

- hosts: all
  vars:
    http_proxy: "http://wwwproxy.sandia.gov:80"
    https_proxy: "http://wwwproxy.sandia.gov:80"
  gather_facts: True
  remote_user: scarroy
  become: no
  become_user: root
  become_method: sudo

  tasks:
    - name: ping the server
      ping:
